### ISSUE TITLE
Compatibility with Bootstrap 4 final?

### ISSUE THREAD

**Issue by jmsche** [ankythshukla/underexpress#1]
Hi,

Is the kit compatible with the latest and final version of Bootstrap? And even 4.1? 

Thanks

**Comment by oleteacher** [comment]
> Is the kit compatible with the latest and final version of Bootstrap?

I replaced bootstrap (with cdn) using 4.1 and had very few issues. Did notice that cards needed little tweaking and few alignment issues but overall very good. Search Stackoverflow if you run into issues, that is where I corrected the few I encountered. Sorry did not document them, should have in a fork...

**Comment by ankythshukla** [comment]
Updated to latest bootstrap 4.1.1.
